### ISSUE TITLE
Lock adjacent Stations

### ISSUE THREAD

**Issue by bennorskov** [bennorskov/ridershipGame#5]
If you get 2 or more in a row, should they lock in?

**Comment by willtscott** [comment]
I'm not sure. That would make the game easier, for sure. Maybe more educational as well. You tell me, you're the one with the degree!

I've organized the stationOrder so that they are now displayed in order of ridership, so that step's done. Without thinking about it much, it seems that it would be a bit tricky to lock adjacent ones.....

**Comment by willtscott** [comment]
If we do this, it should definitely look like the combined Materia slots in FF7!

**Comment by willtscott** [comment]
This works now!
