### ISSUE TITLE
Figure out github hosting page

### ISSUE THREAD

**Issue by bennorskov** [bennorskov/ridershipGame#8]

**Comment by willtscott** [comment]
I looked into this, and it according to instructions on pages.github.com our index.html file should already be live at the url:

http://bennorskov.github.io/ridershipGame/

but it's throwing a 404. 

I get a different error message when trying to access:

http://willtscott.github.io/ridershipGame/

Maybe github pages need to be set up for bennorskov username? I think this is the case, since bennorskov.github.io is also a 404 and mine is the sample page I created during the tutorial.

This might help to get started:
https://help.github.com/articles/creating-project-pages-using-the-command-line/

**Comment by bennorskov** [comment]
I've turned it on now in the repo's settings. I'll check it in a few hours to see if there's a lag time for the setup.

**Comment by willtscott** [comment]
It's working! It's woorrrkkkingggg!
